registry:
    class: lymph.discovery.zookeeper:ZookeeperServiceRegistry
    zkclient: dep:kazoo


event_system:
    class: lymph.events.kombu:KombuEventSystem
    transport: amqp
    hostname: rabbitmq


dependencies:
    kazoo:
        class: kazoo.client:KazooClient
        hosts: zookeeper

instances:
    monkey:
        command: lymph instance --interface lymph.chaos.interfaces:Chaos --reload
    echo:
        command: lymph instance --interface echo:Echo --reload
    demo:
        command: lymph instance --interface demo:Client --reload
